import angular from 'angular';

import 'angular-ui-router';

// Import our templates file (generated by Gulp)
import './config/app.templates';

const requires = [
  'ui.router',
  'templates'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
